version: 1
frontend:
  phases:
    preBuild:
      commands:
        - npm install
        - npm run lint
        - npm audit --audit-level=high
        - curl -sSfL "https://github.com/gitleaks/gitleaks/releases/download/v8.24.3/gitleaks_8.24.3_linux_x64.tar.gz" | tar -xz
        - chmod +x gitleaks
        - sudo mv gitleaks /usr/local/bin/
        - gitleaks detect --verbose
        - pip install semgrep==1.81.0
        - SEMGREP_FORCE_PYSEMGREP=true semgrep scan --config auto --verbose
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: out
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
